name: r2ai
version: '0.9.4'
summary: local language model for radare2
description: |
  Run a language model in local, without internet, to entertain you or help answering questions about radare2 or reverse engineering in general.
  Note that models used by r2ai are pulled from external sources which may behave different or respond unrealible information.
  That's why there's an ongoing effort into improving the post-finetuning using memgpt-like techniques which can't get better without your help!
website: https://www.radare.org/
issues: https://github.com/radareorg/r2ai/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/r2ai-snap
license: LGPL-3.0-only
base: core24
grade: stable
confinement: strict
environment:
  HOME: $SNAP_USER_COMMON
  XDG_CONFIG_HOME: $SNAP_USER_COMMON/config
  XDG_CACHE_HOME: $SNAP_USER_COMMON/cache
  XDG_DATA_HOME: $SNAP_USER_COMMON/data
  XDG_STATE_HOME: $SNAP_USER_COMMON/state
  TRANSFORMERS_NO_ADVISORY_WARNINGS: "1"
apps:
  r2ai:
    command: bin/r2ai
    plugs:
      - network
      - network-bind
      - opengl
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
    # armhf:
    #   build-on: [armhf]
    #   build-for: armhf
    # ppc64el:
    #   build-on: [ppc64el]
    #   build-for: ppc64el
    # riscv64:
    #   build-on: [riscv64]
    #   build-for: riscv64
    # s390x:
    #   build-on: [s390x]
    #   build-for: s390x
parts:
  r2ai:
    plugin: python
    source: https://github.com/radareorg/r2ai.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      # only used when prebuild pip packages are missing
      - cmake
      - libffi-dev
      - libprotobuf-dev
      - libsentencepiece-dev
      - pkg-config
    stage-packages:
      - libffi8
      - libgomp1
      - libprotobuf-lite32t64
      - libsentencepiece0
      - on amd64:
          - libgomp-plugin-amdgcn1
          - libgomp-plugin-hsa1
          - libgomp-plugin-nvptx1
      - on arm64:
          - libgomp-plugin-nvptx1
